# Form implementation generated from reading ui file 'help_menu.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Help_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 661)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uiHeadingTB = QtWidgets.QTextBrowser(self.centralwidget)
        self.uiHeadingTB.setGeometry(QtCore.QRect(60, 30, 201, 31))
        self.uiHeadingTB.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.uiHeadingTB.setObjectName("uiHeadingTB")
        self.uiDescriptionTB = QtWidgets.QTextBrowser(self.centralwidget)
        self.uiDescriptionTB.setGeometry(QtCore.QRect(60, 70, 711, 151))
        self.uiDescriptionTB.setAutoFillBackground(False)
        self.uiDescriptionTB.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.uiDescriptionTB.setObjectName("uiDescriptionTB")
        self.rulesHeadingTB = QtWidgets.QTextBrowser(self.centralwidget)
        self.rulesHeadingTB.setGeometry(QtCore.QRect(60, 250, 201, 31))
        self.rulesHeadingTB.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.rulesHeadingTB.setObjectName("rulesHeadingTB")
        self.rulesDescriptionTB = QtWidgets.QTextBrowser(self.centralwidget)
        self.rulesDescriptionTB.setGeometry(QtCore.QRect(60, 290, 711, 151))
        self.rulesDescriptionTB.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.rulesDescriptionTB.setObjectName("rulesDescriptionTB")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(60, 490, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NLHUTH Poker Bot"))
        self.uiHeadingTB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">User Interface Help</span></p></body></html>"))
        self.uiDescriptionTB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">When you start the poker bot you will be presented with a screen containing three buttons &quot;Call&quot;, &quot;Raise&quot; and &quot;Fold&quot;. Pressing on one of the buttons &quot;Call&quot; or &quot;Fold&quot; will execute the action call and fold respectively. Pressing on raise will change the buttons to &quot;Raise Pot&quot;, &quot;Raise 2 Pot&quot;, &quot;Raise 3BB&quot; and &quot;All in&quot;. Pressing on raise pot</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">will increase the pot by the current pot value, raise 2 pot raises the pot by twice the current value of the pot, raise 3BB increases the current pot value by 3BB (6). All in increases the pot by the value in player chips, i.e. your entire stack. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Options Menu</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:700;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">The two main options &quot;Opponent Model&quot; and &quot;Run length&quot; can be toggled. The default values used in the program are equity model and short run length. The opponent model determines the pretrained model used in selfplay, with the equity model being the result of training against an equity agent and random model being the result of training against a random agent. The run length determines the number of steps to play against the bot for, with short being 1000 steps and long being 10000 steps.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:700;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:700;\"><br /></p></body></html>"))
        self.rulesHeadingTB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Poker Rules</span></p></body></html>"))
        self.rulesDescriptionTB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">We assume that you are familiar with the rules of Poker if you are using this program. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">However, if you are unfamiliar with the rules of Poker there are many good guides available, e.g. </span><a href=\"https://www.officialgamerules.org/texasholdem\"><span style=\" font-size:12pt; text-decoration: underline; color:#0000ff;\">https://www.officialgamerules.org/texasholdem</span></a><span style=\" font-size:12pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">(Note: this program is for the no limit heads up variant, i.e. there is no limit on the amount you can raise by and played between two players).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.backButton.setText(_translate("MainWindow", "Back"))
