# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Menu_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 762)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 140, 0)")
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(650, 380, 131, 41))
        self.startButton.setStyleSheet("background-color: white;\n"
"color: black;")
        self.startButton.setObjectName("startButton")
        self.optionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.optionsButton.setGeometry(QtCore.QRect(650, 440, 131, 41))
        self.optionsButton.setStyleSheet("background-color: white;\n"
"color: black;")
        self.optionsButton.setObjectName("optionsButton")
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(650, 500, 131, 41))
        self.helpButton.setStyleSheet("background-color: white;\n"
"color: black;")
        self.helpButton.setObjectName("helpButton")
        self.pokerMenuSprite = QtWidgets.QLabel(self.centralwidget)
        self.pokerMenuSprite.setGeometry(QtCore.QRect(470, 140, 511, 221))
        self.pokerMenuSprite.setText("")
        self.pokerMenuSprite.setPixmap(QtGui.QPixmap("../res/sprites/icons/poker-aces-clipart-md.png"))
        self.pokerMenuSprite.setObjectName("pokerMenuSprite")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NLHUTH Poker Bot"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.optionsButton.setText(_translate("MainWindow", "OPTIONS"))
        self.helpButton.setText(_translate("MainWindow", "HELP"))
