# Form implementation generated from reading ui file 'options_menu.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Options_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 661)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.modelText = QtWidgets.QTextBrowser(self.centralwidget)
        self.modelText.setGeometry(QtCore.QRect(120, 135, 181, 41))
        self.modelText.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.modelText.setObjectName("modelText")
        self.randomRBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.randomRBtn.setGeometry(QtCore.QRect(330, 140, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.randomRBtn.setFont(font)
        self.randomRBtn.setObjectName("randomRBtn")
        self.equityRBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.equityRBtn.setGeometry(QtCore.QRect(470, 140, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.equityRBtn.setFont(font)
        self.equityRBtn.setObjectName("equityRBtn")
        self.runLenText = QtWidgets.QTextBrowser(self.centralwidget)
        self.runLenText.setGeometry(QtCore.QRect(120, 195, 151, 31))
        self.runLenText.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.runLenText.setObjectName("runLenText")
        self.shortRBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.shortRBtn.setGeometry(QtCore.QRect(330, 200, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shortRBtn.setFont(font)
        self.shortRBtn.setObjectName("shortRBtn")
        self.longRBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.longRBtn.setGeometry(QtCore.QRect(470, 200, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.longRBtn.setFont(font)
        self.longRBtn.setObjectName("longRBtn")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(120, 450, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.infoIcon = QtWidgets.QLabel(self.centralwidget)
        self.infoIcon.setGeometry(QtCore.QRect(120, 320, 31, 31))
        self.infoIcon.setText("")
        self.infoIcon.setPixmap(QtGui.QPixmap("../res/sprites/icons/ic_info.png"))
        self.infoIcon.setObjectName("infoIcon")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 320, 301, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NLHUTH Poker Bot"))
        self.modelText.setToolTip(_translate("MainWindow", "<html><head/><body><p style=\"color:white\">Bot model type: equity is more intelligent and random is less intelligent (see help for more info)</p></body></html>"))
        self.modelText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Opponent Model:</span></p></body></html>"))
        self.randomRBtn.setText(_translate("MainWindow", "Random"))
        self.equityRBtn.setText(_translate("MainWindow", "Equity"))
        self.runLenText.setToolTip(_translate("MainWindow", "<html><head/><body><p style=\"color:white\">Run length, short is 1000 steps and long is 10000 steps (see help for more info)</p></body></html>"))
        self.runLenText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:700;\">Run length</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.shortRBtn.setText(_translate("MainWindow", "Short"))
        self.longRBtn.setText(_translate("MainWindow", "Long"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "Hover over bold text for extra info"))
